name: tie_fp
description: Functional Opinionated library for Flutter
version: 0.0.2

homepage: https://github.com/unacorbatanegra/tie_fp

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  test: ^1.21.0

flutter:
