name: tie_fp
description: Functional Opinionated library for Flutter
version: 0.0.4

homepage: https://github.com/unacorbatanegra/tie_fp

issue_tracker: https://github.com/unacorbatanegra/tie_fp/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  
 
dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1


flutter:
